DROP DATABASE IF EXISTS btc_db;
CREATE DATABASE btc_db;

USE btc_db;

/* CREATE TABLE book_clubs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  active BOOLEAN NOT NULL,
  book VARCHAR(30)
);

CREATE TABLE books_read (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  author VARCHAR(30) NOT NULL,
  description VARCHAR(500) NOT NULL,
);

CREATE TABLE current_club (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  active BOOLEAN NOT NULL,
  book VARCHAR(30)
); */